name = "ez-world-info"
main = "src/index.ts"
compatibility_date = "2024-12-01"

kv_namespaces = [
  { binding = "EZ_WORLD_INFO_KV", id = "bac5429ffe984baa9a4f2ff99f8f6f7e" }
]

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true



